### ISSUE TITLE
ImportError: No module named staticfileshappenings

### ISSUE THREAD

**Issue by engineervix** [wreckage/django-happenings#27]
Hi, I'm just from installing `django-happenings` via pip, and followed instructions as documented on [github](https://github.com/wreckage/django-happenings). However, when it comes to the part where I have to run `./manage.py migrate` to create the models, I'm getting a `ImportError: No module named staticfileshappenings`. 
I'm stuck! What could be the problem? I'm using Python 2.7 ([Homebrew](http://brew.sh)) and Django 1.9.9 on a Mac (El Capitan). Details of the error are as shown below:

```bash
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/user/virtualenvs/this_env/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/user/virtualenvs/this_env/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Users/user/virtualenvs/this_env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/user/virtualenvs/this_env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/user/virtualenvs/this_env/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named staticfileshappenings
```

**Comment by engineervix** [comment]
resolved. The problem is that I left out a comma (,) after the previous entry on `INSTALLED_APPS` in the settings!
